name: Run Model Training
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 355
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib seaborn requests
      - name: Configure matplotlib
        run: |
          echo "backend: Agg" > matplotlibrc
          export MPLBACKEND=Agg
      - name: Log setup time
        run: echo "Setup completed at $(date)"
      - name: Run training script
        run: |
          sleep 1
          python train_model.py &
      - name: Wait and trigger next run
        run: |
          sleep 100  # Wait 100 seconds for testing
          echo "Triggering next workflow run"
        continue-on-error: true
      - name: Trigger self
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Context:', JSON.stringify(context, null, 2));
            let workflowId = 'main.yml'; // Fallback
            if (context.workflow_ref) {
              workflowId = context.workflow_ref.split('/').pop().split('@')[0];
            }
            console.log(`Using workflow_id: ${workflowId}`);
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              ref: 'main'
            });
        continue-on-error: true
